Repository jumpserver/koko, pull requests merged in 2020-09, with the labels that each got.

#421 perf: 修正宽度高度
  static/js/koko.js
  templates/ssh/terminal.html
Labels: 优化

#423 Dev
  entrypoint.sh
  locale/zh_CN/LC_MESSAGES/koko.po
  pkg/httpd/webserver.go
  static/js/koko.js
  templates/ssh/terminal.html
Labels: 无需处理

#425 chore: Dev to master
  README.md
Labels: 无需处理

#427 chore: Dev to master
  config_example.yml
  static/js/koko.js
Labels: 无需处理

#436 fix: redis conn bug
  pkg/exchange/redis.go
Labels: fix
