Repository jumpserver/koko, pull requests merged in 2022-09, with the labels that each got.

#941 feat: 支持连接开启了ssl的Redis数据库
  pkg/proxy/server.go
  pkg/srvconn/conn_redis.go
Labels: 类型:新功能

#945 perf: 支持连接开启ssl且自签证书的Redis/MongoDB
  pkg/jms-sdk-go/model/application.go
  pkg/proxy/server.go
  pkg/srvconn/conn.go
  pkg/srvconn/conn_mongodb.go
  pkg/srvconn/conn_mysql.go
  pkg/srvconn/conn_redis.go
Labels: 类型:优化

#947 perf: 屏蔽--secure参数，目前redis-cli版本为6.0，暂时用不到
  pkg/proxy/server.go
  pkg/srvconn/conn_redis.go
Labels: 类型:优化

#952 feat: 主题设置增加默认主题选项
  ui/src/components/ThemeConfig.vue
  ui/src/utils/common.js
  ui/src/views/Connection.vue
  ui/src/views/ShareTerminal.vue
Labels: 类型:新功能

#950 fix: 解决使用ES且故障时，在线会话命令丢失的问题
  pkg/proxy/recorder.go
Labels: 类型:bug
